- README.md
Added note to explain the reason of the move of the repo.
If there is no other addition i think we can make this repo public + publishing on npm. Just need to ensure we want to use namespace which will break the `fastify-*` naming convention.
> doc: add note

- README.md
npm badge was still refering to old repository.
> doc: fix npm badge

- lib/fastifySession.js
- test/base.test.js
- test/session.test.js
- test/store.test.js
Port of https://github.com/SerayaEryn/fastify-session/pull/147. Original OP below.
---
Being able to access the session data in any `onRequest` hook is useful (in my case _needed_ since we still use `fastify-express` which only runs in that hook).
> feat: set up session in `onRequest` rather than `preValidation`

- README.md
- types/test/basic.ts
- types/test/session-type.ts
- types/types.d.ts
Port of https://github.com/SerayaEryn/fastify-session/pull/145, original OP below.
---
Picks up typos like `session.sessionID` (which is what it's called in `express-session`).
Possibly breaking change, but I wouldn't say so
> fix(types): disallow unknown properties on session

- test/base.test.js
Resolves #37: This PR changes the test title of "should set session cookie on post without params" to "should not set session cookie on post without params", and adds assertions that the session cookie is not set.
> fix: incorrect title for session cookie test

- README.md
- lib/session.js
- test/session.test.js
- types/types.d.ts
- types/types.test-d.ts
This PR adds `get`, `set` methods for using the session. 
These methods are need for integration with `fastify-passport` (See https://github.com/fastify/fastify-passport/pull/421)
> Add Get/Set methods

- README.md
- lib/fastifySession.js
- test/session.test.js
--
Addresses #17
Also, see [this](https://github.com/fastify/help/issues/511) issue and [this](https://github.com/SerayaEryn/fastify-session/issues/106) one.
There are certain cases where the developer might want cookie options specific to a particular session, e.g. set `maxAge` if this user checked "remember me". This PR adds a `cookieOpts` argument to the `decryptSession` decorator so the developer can manually specify cookie parameters on a per-session basis using whatever business logic they so choose.
> feat: session cookie opts

- types/types.d.ts
- types/types.test-d.ts
Hello.
This PR aims to :
- fix `CookieOptions` types
- avoid callbacks types bad practices
- make types compatible with `express-session` stores (see: https://github.com/fastify/help/issues/604)
> fix (types): fix callbacks types and ensure compatibility with `express-session` stores

- README.md
- lib/fastifySession.js
- lib/session.js
- test/session.test.js
- types/types.d.ts
- types/types.test-d.ts
Fix for #62 
Added the request object to the idGenerator function for custom scenarios like:
```js
idGenerator: (request) => {
if (request.session.returningVisitor) return `returningVisitor-${uid(24)}`
else return uid(24)
}
```
> idGenerator request object (#62)

- .github/workflows/ci.yml
- package.json
- test/secret.test.js
- test/session.test.js
Ava removed `test.cb` function in ava@4v as you can see on this [doc](https://github.com/avajs/ava/blob/8571b2a7f7ebfefcdc014e7a43b6c874b765b722/docs/02-execution-context.md#tend)
> chore: fix tests due major ava update

- .github/workflows/ci.yml
- package.json
- test/secret.test.js
- test/session.test.js
- test/store.test.js
- test/util.js
This reverts commit da33d5dc8ce8f722092db9fd85c33724e73f0b77.
This PR target to `6.x` branch and revert the drop support changes as I release the wrong version number.
It should not drop the support of node 10 for `6.x`.
> Revert "major: drop node 10 and ava update (#65)"

- README.md
- lib/fastifySession.js
- lib/session.js
- test/session.test.js
- types/types.d.ts
- types/types.test-d.ts
I have not added tests yet, other than that I think this is ready to go. Opening it up early in case there's feedback before I spend time writing tests 🙂 
Fixes #34
> feat: add `destroy`, `save` and `reload` to session instance

- README.md
- lib/session.js
- test/session.test.js
- types/types.d.ts
- types/types.test-d.ts
Fixes #24.
~(note that this includes #77, so just review the last commit)~
> feat: Promise API

- lib/fastifySession.js
- test/session.test.js
- test/util.js
I noticed while using a memory storage that the old session cookie was kept around. Doesn't really hurt, but it confused me when I was debugging why my session wasn't working
> feat: remove stale cookies

- README.md
- lib/fastifySession.js
- lib/session.js
- test/base.test.js
- test/session.test.js
- test/store.test.js
- types/types.d.ts
Moving the `expires` property out of session and into cookie for compatibility with express-session.
See discussion here:
https://github.com/fastify/session/pull/101#discussion_r909433854
Only look at most recent commit. This PR is dependent on test cleanup being merged first:
https://github.com/fastify/session/pull/117
No noticeable benchmark differences
> Move `expires` from session to session.cookies

- README.md
- lib/fastifySession.js
- lib/idGenerator.js
- package.json
- test/idGenerator.test.js
- types/types.d.ts
my server to run the benchmarkr
```
'use strict'
const Fastify = require('fastify')
const fastifySession = require('..')
const fastifyCookie = require('@fastify/cookie')
const fastify = Fastify()
fastify.register(fastifyCookie)
fastify.register(fastifySession, {
secret: 'cNaoPYAwF60HZJzkcNaoPYAwF60HZJzk',
cookie: { secure: false }
})
fastify.get('/', async (request, reply) => {
reply
.send(request.cookies.sessionId)
})
fastify.listen({ port: 3000 })
```
before:
```
autocannon  http://127.0.0.1:3000Running 10s test @ http://127.0.0.1:3000
10 connections
┌─────────┬──────┬──────┬───────┬──────┬─────────┬─────────┬───────┐
│ Stat    │ 2.5% │ 50%  │ 97.5% │ 99%  │ Avg     │ Stdev   │ Max   │
├─────────┼──────┼──────┼───────┼──────┼─────────┼─────────┼───────┤
│ Latency │ 0 ms │ 0 ms │ 0 ms  │ …
```
> perf: improve idgenerator (about 25-30 % faster)

- lib/session.js
extracted from #118 made by @rclmenezes 
it really makes no sense to extract it to a separate function, and it makes no sense to create for each Session instantiation an empty Object.
> chore: remove addDataToSession

- lib/fastifySession.js
- lib/session.js
- test/base.test.js
- test/session.test.js
> Remove session id round 4

- lib/store.js
Reverts fastify/session#122
If it is a ES6 class it will have regressions, as some store implementations dont extend the store class but call the function instead. This results that the benchmarks failed
see https://github.com/valery-barysok/session-file-store/blob/b89a42b00f24e720bb9d07cc7ddf72ef6c43c7bc/lib/session-file-store.js#L26
> Revert "refactor store to es6 class"

- test/session.test.js
@rclmenezes 
Why does it pass? :D
> add unit test for maxAge

- lib/store.js
- test/memorystore.test.js
- test/store.test.js
I want to restructure the unit tests. This one is the beginning.
> create a separate unit test file for memorystore

- lib/cookie.js
- lib/session.js
- test/cookie.test.js
This PR makes maxAge being preferred over expires, like we documented it in the readme.md. The reason why it worked as documented, was that we do a .touch() when we instantiated a Session. So I removed the .touch() and fixed the getExpires method. 
@rclmenezes 
> use maxAge over expires

- lib/cookie.js
- lib/fastifySession.js
- lib/session.js
- test/base.test.js
- test/cookie.test.js
- test/session.test.js
- test/store.test.js
Edit: I'm breaking up this PR, setting back to draft.
- To do this, we need to make sure that cookie.expires is used in the cookie hash
- This in turn, required that expires be an actual Date in our tests
See issue: https://github.com/fastify/session/issues/147
> Resave session cookie if saveUninitialized is false and rolling is true

- lib/fastifySession.js
- lib/session.js
- test/session.test.js
It seems that in some cases the request is not decorated with the sessionStore. Instead we keep now a reference to the sessionStore directly and access the sessionStore instead of always accessing it through the request-Object. 
> Make it possible to call save() in decryptSession

- lib/fastifySession.js
Related to issue #163 .
The deprecation of `decryptSession` is reversed to support scenarios where node services can be hybrid and can potentially have the need to share the sessions between Fastify and other libraries like socket.io.
- [X ] run `npm run test` and `npm run benchmark`
- [X ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
> Remove deprecation notice for fastify-Instance decryptSession

- lib/fastifySession.js
- test/verifyPath.test.js
This PR ensures that we respect the path of the session. So we dont load the session if the cookie is sent to a different path. 
when is it relevant?
If I set the cookie to the path `/admin` and send it to `/admin-ui`, it was previously loading the session. 
> security: verify path of cookie/session

- lib/fastifySession.js
- test/session.test.js
This PR fixes the issue #173. If user specifies `domain` in a cookie, but runs the server behind a subdomain, then a duplicate empty cookie is created at the specified condition and it will always be used for the following HTTP requests as a SID cookie, breaking the session mechanism.
> fix: set domain when clearing cookie

- types/types.d.ts
now Session actually resolves to the session interface defined in the same files instead of being an unresolved any. goal of this change is to fix #181 
before:
after:
This doesn't require a new test/benchmark or doc change to the best of my knowledge.
> types: fix Session interface reference

- README.md
- package.json
- types/types.d.ts
- types/types.test-d.ts
This PR was motivated by the current need to assert that the Store types are `any` due to the incompatibility of @fastify/session's types with express-session's. e.g.
```ts
server.register(fastifySession, {
store: new RedisStore({
client: redisClient,
}) as any,
```
I tried to keep the changes to a minimum, but it was necessary to alter the callbacks types and to change precisely what was in the various Session types.
The callback needed updating because express-session's callbacks all define their errors as `any` and because we can't guarantee that a `session` is passed to the callback.
The Session types needed updating because the stores are only compatible with express-session's `SessionData` …
> fix: express session type compatibility

- README.md
- lib/session.js
- test/session.test.js
- types/types.d.ts
- types/types.test-d.ts
You can pass an array of fields that should be kept when the session is regenerated
> feat: add ignoreFields option to regenerate method

- lib/fastifySession.js
- test/verifyPath.test.js
I encountered a problem that cookie.path option didn't work if:
1. Path was longer then just "/".
2. Get request had a query parameters.
> fix: separate an actual path from url search part before verification

- lib/session.js
- test/session.test.js
Following up #80. We're seeing some data loss after updating the session in a distributed, and the suspect is `onSend` in this library storing old data, overwriting the update performed by either a different concurrent request, or a request handled by another pod.
Note that this is slightly different from what `express-session` does.
https://github.com/expressjs/session/blob/1010fadc2f071ddf2add94235d72224cf65159c6/index.js#L403-L407
It tracks `modified` and `saved` separately. I'm not sure if that is necessary?
> fix: manually persisting the session should make `isModified` return false

- lib/fastifySession.js
- test/session.test.js
In this PR, I have fixed an issue where the session is not saved when request.session.cookie.expires is null.
Previously, `rollingSessions || (Boolean(request.cookie.expires) && request.session.isModified())` was evaluated when `cookieId === request.session.encryptedSessionId`, that is, when the session already exists.
However, it seems that cookie.expires is not related to saving the session. Therefore, I have removed the process that evaluates cookie.expires.
This process was implemented in #149, but before that, cookie.expires was not evaluated.
> fix: remove cookie.expires from shouldSaveSession evaluation logic

- benchmark/bench.js
- lib/idGenerator.js
- lib/session.js
- lib/store.js
- test/fastifySession.checkOptions.test.js
- test/memorystore.test.js
See https://github.com/fastify/fastify-static/pull/407
> perf: use `node:` prefix to bypass require.cache call for builtins

- lib/fastifySession.js
See https://github.com/fastify/fastify/pull/5057
> perf(lib/fastifysession): optimize split param

- examples/redis.js
Updated the redis-connect import as per docs.
All tests passed:
> Updated import as per redis-connect docs

- types/types.d.ts
Not sure if there's a way to this without creating an extra interface
Closes #213
> export cookie types

- types/types.d.ts
- types/types.test-d.ts
> export the correct cookie options interface

- README.md
- lib/cookie.js
- package.json
- test/cookie.test.js
Related to https://github.com/fastify/session/issues/213
npm run benchmark -> failed
TypeError: redisStoreFactory is not a function
at createServer (C:\GitHub\fastify-session\benchmark\bench.js:19:24)
at testFunction (C:\GitHub\fastify-session\benchmark\bench.js:56:18)
at main (C:\GitHub\fastify-session\benchmark\bench.js:83:15)
> Fix: add ability to create Partitioned Cookies

- lib/cookie.js
- lib/fastifySession.js
- lib/isConnectionSecure.js
- test/cookie.test.js
- test/util.js
The header shouldn't be read unless `trustProxy` is true.
> fix: use request.protocol to check for HTTPS

- test/cookie.test.js
Fixes the race condition that caused tests to fail for https://github.com/fastify/session/pull/241
> fix race condition in cookie.maxAge test

- types/types.d.ts
- types/types.test-d.ts
- This PR is meant to replace #227
- This PR is a two step plan to fix the `maxAge` unit issue. See follow-up step in #244
> Ensure maxAge type has milliseconds as the unit

- lib/fastifySession.js
- test/fastifySession.checkOptions.test.js
I passed a Buffer instead of a string as a secret, and this resulted in an error message that "cookieSigner.sign is not a function" an at request time, rather than at plugin registration.
Someone else had a similar issue in the past https://github.com/fastify/help/issues/852
This PR makes `checkOptions` more comprehensive (explicitly checking for `.sign` and `.unsign` methods on signer objects passed as options.secret), and adds associated tests, so that this error is caught sooner and with a helpful message :)
- [n/a] documentation is changed or added
> enhance checkOptions to reject invalid signer objects

- benchmark/bench.js
The current `npm run benchmark` isn't working.
As stated in [Release v7.0.0 · tj/connect-redis](https://github.com/tj/connect-redis/releases/tag/v7.0.0), there is a breaking change about importing the package.
This PR fixes that.
> fix: `npm run benchmark` isn't working

- types/types.d.ts
- types/types.test-d.ts
The current generic method `session.get(key)` accidentally allows the return value to be inferred into any type.
The `session.set(key, value)` also allows `value` of any type to be passed in.
**Note:** This fix removes the second generic param `V`, so it will break an undocumented usage for TypeScript users specifying both two generic type parameters. (This should be rare.)
> Fix type argument inference of `session.get(key)` and `session.set(key, value)`
