- README.md
- lib/fastifySession.js
- types/test/using-store.ts
- types/types.d.ts
This pull request does
1) Resolve FastifyDeprecation warning, used https://github.com/SerayaEryn/fastify-session/pull/143
2) Added typescript documentation about the custom sessions.
3) Removed deprecated FastifyPlugin import and instead added FastifyPluginCallback.
> Resolved FastifyDeprecation warning and added typescript documentation.

- .nycrc
- README.md
> feat: enforce coverage 100%

- types/types.d.ts
Port of https://github.com/SerayaEryn/fastify-session/pull/146. Original OP below.
---
It's exported by the code: https://github.com/fastify/session/blob/4e3cd1453808bd6e8298308ddcd30e5c5d6f1ea6/lib/fastifySession.js#L206-L208
> feat(types): export Store class

- types/types.d.ts
- types/types.test-d.ts
> fix: idGenerator isn't in the options type.

- README.md
> Docs: typescript issues with some express-session compatible stores

- test/base.test.js
- test/cookie.test.js
- test/store.test.js
Extends token limitation to fix tests flakiness.
> fix: regex limitation

- types/types.d.ts
- types/types.test-d.ts
https://github.com/fastify/session/pull/61#issuecomment-1077885306
> fix(types): error is optional, and session data always exists

- README.md
- lib/session.js
- test/session.test.js
- types/types.d.ts
- types/types.test-d.ts
I'm working on #34, but this change seems like something that's safe on its own? Not sure if it should be considered a breaking change - if the argument is passed it's just ignored. TS will complain though
> fix: remove request argument from Session#regenerate

- lib/fastifySession.js
- test/session.test.js
- types/types.d.ts
- types/types.test-d.ts
This PR increments the proposed solution in https://github.com/fastify/session/pull/71 by adding specific tests for the new flag and validating session is maintained throughout requests even if the cookie sent by the client had been previously signed.
Closes #69.
> feat: add support for handling previously-signed cookies

- types/types.test-d.ts
Every other line in this file has an explicit semlicolon.
This will stop all the static analysis tools from moaning.
> style(types/types.test-d.ts): explicitly declare semicolon

- lib/fastifySession.js
- lib/metadata.js
small change, makes it more uniform with other plugins
> remove metadata.js

- .github/workflows/ci.yml
- package.json
activate lint and license-check in ci pipeline
> separate lint from npm test script, activate lint and license-check in ci pipeline

- .taprc
> tap should only run test.js files

- test/base.test.js
- test/cookie.test.js
- test/secret.test.js
- test/session.test.js
- test/store.test.js
- test/util.js
> Clean up tests

- lib/fastifySession.js
No noticeable benchmark change.
> Simplify shouldSaveSession code a little bit

- lib/store.js
Everything else is es6 class except the store.
> refactor store to es6 class

- types/types.d.ts
> simplify callback typing

- examples/memory.js
I use this for running realistic benchmarks.
> add autocannon example

- lib/fastifySession.js
@climba03003 mentioned to me that it would be potentially better to load Signer if it is actually needed 
This PR implements this idea.
> move signer require into ensureDefaults

- lib/fastifySession.js
- test/session.test.js
- test/util.js
I really dont know how to describe this issue. I dont know why I need to pass a new Object for register. If I just pass sessionOptions directly then the fixed unit test will fail. Super strange, and makes me wonder if there is any documentation regarding this odd behaviour in fastify core?
> fix unit test

- types/types.test-d.ts
> fix lgtm alert

- lib/cookie.js
> simplify getExpires, export getExpires from cookie

- lib/fastifySession.js
- lib/session.js
@rclmenezes 
any thoughts on this?
It makes it obvious that rolling is basically not implemented I guess.
> remove internal used session restore() function

- package.json
- test/session.test.js
> remove sinon as dev dependency

- examples/redis.js
> add redis example

- lib/fastifySession.js
Something which really annoyed me from the beginning :)
> rename session to fastifySession

- lib/cookie.js
- lib/session.js
- test/cookie.test.js
- test/session.test.js
Shamelessly copied from the repository of @rclmenezes 
> Implement originalMaxAge

- types/types.d.ts
- types/types.test-d.ts
We were missing typings for decryptSession.
> add typings for decryptSession

- lib/fastifySession.js
> minor cosmetic change

- lib/getCookieOpts.js
- test/cookie.test.js
> ensure that secure false is not overwritten by null

- README.md
> Little remark  fastify-cookie -> @fastify/cookie

- lib/fastifySession.js
- types/types.d.ts
- types/types.test-d.ts
> nodenext compatibility

- README.md
- lib/session.js
- test/session.test.js
- types/types.d.ts
- types/types.test-d.ts
backport of https://github.com/fastify/session/pull/189
> backport: regenerate session

- README.md
- types/types.d.ts
- types/types.test-d.ts
> feat!: stricter types

- README.md
- lib/fastifySession.js
- lib/session.js
- test/session.test.js
See https://github.com/fastify/session/pull/201#issuecomment-1618836838
> fix: make sure to set cookie on manual session saves

- examples/redis.js
> chore: update redis example

- README.md
I ran into
``
Property 'session' does not exist on type 'FastifyRequest<RouteGenericInterface, RawServerDefault, IncomingMessage, FastifySchema, FastifyTypeProviderDefault, unknown, FastifyBaseLogger, ResolveFastifyRequestType<...>>'.
``
for half an hour, because I used ``const fastifySession = require("@fastify/session")`` rather than ``import { fastifySession } from '@fastify/session';``.  The ``require`` won't work with TypeScript's declaration merging.
Adding this documentation will probably save someone some time :P
```ts
// Use module imports rather than commonjs' require for correct declaration merging in TypeScript. 
// Wrong ❌:
// const fastifySession = require('@fastify/session');
// const fastifyCookie = require('@fastify/cookie');
// Correct ✔️:
import { fastifySession } from …
```
> Added documentation for import of modules w/ declaration merging

- .github/workflows/ci.yml
- package.json
> Merge `next` into `master`
